# Generated by Django 4.1.7 on 2023-02-27 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20)),
                ('origin_country', models.CharField(max_length=50)),
                ('origin_city', models.CharField(max_length=50)),
                ('origin_airport_code', models.CharField(max_length=10)),
                ('destination_country', models.CharField(max_length=50)),
                ('destination_city', models.CharField(max_length=50)),
                ('destination_airport_code', models.CharField(max_length=10)),
                ('date_time_origin', models.DateTimeField()),
                ('date_time_destination', models.DateTimeField()),
                ('total_seats', models.IntegerField()),
                ('seats_left', models.IntegerField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_seats', models.IntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.user')),
            ],
        ),
    ]
