# Generated by Django 4.1.7 on 2023-02-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0002_remove_flight_id_user_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
