# Generated by Django 4.1.5 on 2023-02-27 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0003_remove_order_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flight_app.flight'),
        ),
    ]
